repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
- repo: https://github.com/pycqa/flake8
  rev: 7.2.0
  hooks:
  - id: flake8
  additional_dependencies: [flake8==7.2.0]
  language_version: python3.9
  exclude: ^bin/
  files: ^src/
- repo: https://github.com/AleksaC/hadolint-py
  rev: v2.12.1b3
  hooks:
  - id: hadolint
  args: [--config, .hadolint.yaml]
  exclude: ^src/
- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.10.0.1
  hooks:
  - id: shellcheck
#    args:
#    - --exclude=SC2046
#    - --exclude=SC2006
    exclude: ^src
# - repo: https://github.com/markdownlint/markdownlint
#   rev: v0.13.0
#   hooks:
#   - id: markdownlint
#     args:
#     - --help
